spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb   # H2 ??? ?????? URL


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect   # H2 ?????? ?? ??
    hibernate:
      ddl-auto: create-drop   # ?????? ?? ? ???? ???? ????, ?? ? ????? ?? (????)
    show-sql: true            # JPA? ??? SQL? ??? ????? ?? (?? ? ??)
logging:         # (1) ?? ?? ??
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG